// <auto-generated />
using System;
using Licensing_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licensing_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250305121243_AddActionDataTable")]
    partial class AddActionDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Licensing_Web.Models.ActionTypeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("actionType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "actiontype");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "isactive");

                    b.HasKey("id");

                    b.ToTable("ActionData");
                });

            modelBuilder.Entity("Licensing_Web.Models.ImportDataModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("records")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ImportDataModels");
                });
#pragma warning restore 612, 618
        }
    }
}
