name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .  # This points to the root of your repository
        file: Dockerfile  # Adjust this to the correct location of your Dockerfile
        push: true
        tags: kirubakaran007/licensing_web_poc:testv1.3
