name: CI-build-and-push-image-for-dotnetapp

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug DockerHub Username
        run: |
          echo "🔍 Checking DockerHub Username..."
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "🚨 ERROR: DOCKERHUB_USERNAME is not set in GitHub Secrets!"
            exit 1
          else
            echo "✅ DockerHub Username is set: ${{ secrets.DOCKERHUB_USERNAME }}"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/dockerfordotnetlicense:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/dockerfordotnetlicense:${{ github.run_number }}
